#The docker-compose.yml file describes the services that make your app. 
#In this example those services are a web server and database. 
#The compose file also describes which Docker images these services use, how they link together, 
#any volumes they might need mounted inside the containers. 
#Finally, the docker-compose.yml file describes which ports these services expose. 
#See the docker-compose.yml reference for more information on how this file works.
version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:9090
    volumes:
      - .:/code
    ports:
      - "9090:9090"
    depends_on:
      - db